### ISSUE TITLE
Do not move from current workspace when showing opened hyperterm

### ISSUE THREAD

**Issue by markelog** [CWSpear/hyperterm-visor#10]
In iTerm if you open a window in, for example, second workspace then move focus to first one and then again call `show` hotkey, it will move terminal in the first workspace.

Visor, in contrast, will move focus back to the second workspace again.

Is it possible to implement similar behaviour?

**Comment by CWSpear** [comment]
This was discussed in #6. I haven't been able to find a way in Electron to recognize those different spaces. As far as I can find so far, it's not possible, but I've gotta believe we're not the first ones to come across this...

**Comment by markelog** [comment]
Oh, sorry for duplicate, didn't realize it, thank you for checking it out, hope there will be solution one day
