### ISSUE TITLE
Fullscreen uses only a portion of the vertical space

### ISSUE THREAD

**Issue by fgilio** [CWSpear/hyperterm-visor#18]
Hi!

I tried with `height: 100`, `height: '100'` and `height: '100%'` but could't make Hyper use the hole screen, it always uses a portion of the vertical space.

Am I doing something wrong?
Thanks!

**Comment by CWSpear** [comment]
It isn't documented, but you can actually leave off the `height` and `width` values and set `position` to `full` and that should make it use the full screen.

**Comment by fgilio** [comment]
Awesome!
