### ISSUE TITLE
Fullscreen option

### ISSUE THREAD

**Issue by brandonb927** [CWSpear/hyperterm-visor#2]
Great work on this! I use iTerm2 in Fullscreen mode and that is the one thing missing about Hyperterm that would make me consider using it daily (among other oddities that I'm still trying to get around). Let me know if this is on the roadmap or I can just submit a PR.

Cheers!

**Comment by CWSpear** [comment]
I can definitely do that pretty easy! It honestly hadn't crossed my mind.

And... funny story, if you put anything in the config _other_ than `left`, `right`, `top` or `bottom`, it will cover the full screen -.-

That's unintended, but I will probably add stuff like `full` and `topleft`, etc, soon, so if you use this current version and set the position to `full`, it should actually get you the behavior you're wanting!

Definitely still a few things I need to work out, like a few edge cases where things go weird, and https://github.com/CWSpear/hyperterm-visor/issues/3

**Comment by CWSpear** [comment]
Closing in favor of https://github.com/CWSpear/hyperterm-visor/issues/5

**Comment by brandonb927** [comment]
Great! 🍻
