### ISSUE TITLE
Has this been tested on more recent versions?

### ISSUE THREAD

**Issue by genu** [CWSpear/hyperterm-visor#21]
I'm using Hyper v1.2.1 and this doesn't seem to work at all.

Plugin is enabled, and using the same config as the Readme. 

Anybody else having issues?

**Comment by KarlAmort** [comment]
Worked for me as of 10 minutes ago with the configuration below and the version you mentioned. I switched to hyperterm-overlay just now, though, because I couldn't get -visor to return focus to the previous application (#7).

**Comment by CWSpear** [comment]
@genu should be working with the release you were on, but there is also a new release of this plugin if you wanna give it another try.

@MatthiasWinkelmann that should be the next thing we look at tackling.

**Comment by CWSpear** [comment]
See https://github.com/CWSpear/hyperterm-visor/releases/tag/v0.3.1
