### ISSUE TITLE
§ key binding not working / Invalid key binding removes all key bindings from hyperterm

### ISSUE THREAD

**Issue by GijsGoudzwaard** [CWSpear/hyperterm-visor#22]
hotkey: 'Command+§' not working.

When using an invalid key binding like the one above visor will remove all registered keybindings from hyperterm.

**Comment by CWSpear** [comment]
This is an Electron limitation, I believe. There's a [list of available keys](https://github.com/electron/electron/blob/master/docs/api/accelerator.md#available-key-codes) in their docs. The **Punctuations** list is open ended, but I'm gonna say that `§` is not part of that list.
