### ISSUE TITLE
Opens and closes once, then de-focusses and stops

### ISSUE THREAD

**Issue by kierenj** [CWSpear/hyperterm-visor#28]
I'm on Windows.  I hit my hotkey (Control+F1), it appears - again - it disappears - again- nothing happens.
I need to re-focus another window on my desktop to have the shortcut work again.
I think the fix would be to manually restore focus to the previous window when closing with the shortcut?

**Comment by sabahang** [comment]
Same thing happens to me

**Comment by acristescu** [comment]
Same here... any workarounds?

**Comment by CWSpear** [comment]
This repository is no longer maintained. Feel free to fork. Probably doesn't work with the latest version of Hyper 1, and certainly unlikely to work with Hyper 2.
