### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by philwade** [CWSpear/hyperterm-visor#29]
Previously, with multiple monitors, I was able to hide my terminal on one then open it on another by moving my mouse. Introduced sometime around the switch to `hyperterm-register-shortcut`.

Probably not high priority, but something to look into.

**Comment by jajaperson** [comment]
I would also like support for use on multiple desktops, so that when you switch desktop the Hyper window follows you.

**Comment by CWSpear** [comment]
This repository is no longer maintained. Feel free to fork. Probably doesn't work with the latest version of Hyper 1, and certainly unlikely to work with Hyper 2.
