### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tristanbes** [CWSpear/hyperterm-visor#31]
Hello,

I can't get this plugin to work and that's the final blocking point to use hyper.is to me :(

I'm up-to-date

```
plugins: [
    "hyperline",
    "hypercwd",
    "hyperterm-visor",
    "hyper-alt-click",
    "hyperterm-safepaste",
    "hypertheme",
    "hyperterm-tab-icons",
    "hyperlinks",
    "hyperterm-alternatescroll"
  ],
  visor: {
    hotkey: 'Alt+Space',
    position: 'top', // or left, right, bottom
    width: 200, // Optional, defaults to half of viewable area for horizontal positions, 100% for vertical
    height: 900, // Optional, defaults to half of viewable area for vertical positions, 100% for horizontal
  },
```

Tried a lot of hotkey (`CommandOrControl+Space`...) combinaisons, but none of them are working even with a full hyper.is restart between conf changes.

I have 3 screens and i'm running on OSX 10.12.4

Any idea of what's happening ?

**Comment by MrLoh** [comment]
I can't get this to work either on the same OS. Any help?

**Comment by MrLoh** [comment]
actuallt my mistake was just to not put the visor config at the right place. And neither are you @tristanbes. Plugins is not a subsection of config, but of the global export. But the visor config, needs to go under config, like so. 

```js
module.exports = {
  config: {
    fontSize: 16,
    ...
    visor: {
      hotkey: 'Control+Shift+Space',
      position: 'left'
    }
  },
  plugins: ["hyperterm-visor", "hyperminimal"],
};
```

**Comment by tristanbes** [comment]
omg, @MrLoh thank you, you really removed a painfull issue to me.

![](https://media2.giphy.com/media/l41lZnO2hNzQL9zoY/giphy.gif)
