### ISSUE TITLE
hot key stopped working.

### ISSUE THREAD

**Issue by AlexanderBollbach** [CWSpear/hyperterm-visor#33]
I had "Option+Space" working all this morning.  The next moment it stopped working.

[https://gist.github.com/AlexanderBollbach/8ab50e7fc3396f654f771d7fadab42fd](url)

**Comment by asotog** [comment]
similar here i have `command+shift+h` configured it works fine, but after some time, what it does is opening a new hyper window instead of opening the same

version 1.4.8 on Mac OS 10.11.6

**Comment by CWSpear** [comment]
This repository is no longer maintained. Feel free to fork. Probably doesn't work with the latest version of Hyper 1, and certainly unlikely to work with Hyper 2.
