### ISSUE TITLE
hotkey not working anymore, instead it creates a new hyperterm window

### ISSUE THREAD

**Issue by asotog** [CWSpear/hyperterm-visor#34]
instead of showing the existent window, it creates a new blank hyper, it used to work.

[UPDATE]: something i noticed, is that i have multiple tabs opened, i'm able to reproduce issue like that. On new hyper window with 1 tab it works fine looks like

Info:
OS X Capitan, 10.11,.6
Hyper 1.3.3.1754

**Comment by RTSchriner** [comment]
I'm having this same issue.  I concur, multiple tabs breaks it.

**Comment by asotog** [comment]
similar here i have `command+shift+h` configured it works fine, but after some time, what it does is opening a new hyper window instead of opening the same

version 1.4.8 on Mac OS 10.11.6

**Comment by CWSpear** [comment]
This repository is no longer maintained. Feel free to fork. Probably doesn't work with the latest version of Hyper 1, and certainly unlikely to work with Hyper 2.
