### ISSUE TITLE
Is this plugin still active ?

### ISSUE THREAD

**Issue by asotog** [CWSpear/hyperterm-visor#37]
Is this plugin still active ? so maybe can be noted down in the README to ask for help so other developers can address issues as well

**Comment by CWSpear** [comment]
Pull requests are always welcome. Shouldn't need a note for that.

It's not particularly active. There are other alternatives with more use, and I no longer actively use Hyper.js (just never really got up to snuff for my needs and I went back to using iTerm). It has advanced, and maybe I'll get Hyper another try.

This is noted as pre-1.0 quality software, so bugs and unfinished-ness should be expected.

**Comment by asotog** [comment]
sad :( good to know thanks man
