### ISSUE TITLE
Add more position options

### ISSUE THREAD

**Issue by CWSpear** [CWSpear/hyperterm-visor#5]
I want to support `full`, `topleft`, `topright`, `bottomleft`, `bottomright` and possibly custom dimensions on top of that. i.e. you specify `top`, but you want it 600 x 400px, so it puts it at that size in the center top.

**Comment by Qard** [comment]
I want `full` too. 😸

**Comment by CWSpear** [comment]
@Qard `full` is unofficially supported... give it a try!

**Comment by robinweser** [comment]
Would it also be possible to just keep the window size/position as it was used before? I actually do not want to have a docked window :P

**Comment by CWSpear** [comment]
@rofrischmann just don't set a position :-)

**Comment by CWSpear** [comment]
In version 1.0, I'm deprecating the `position` option in favor of `anchor`. `anchor` makes no assumptions about the _size_ you want (will remember size unless you set a `width` or `height`). It only cares about where the window will appear (it will be anchored where you specify). You can set the anchor to `none` and it won't move the window on activation.

This is _not_ released at the time of this writing. I believe this solution will allow just about everyone to get what they wanted, but wanted help to do a little testing before I go live. Please test out `hyperterm-visor@next` and see if it works as expected or if you can shake out any bugs!

**Comment by RTSchriner** [comment]
@CWSpear: Sure thing! Installing now...

**Comment by CWSpear** [comment]
Note, if you are putting this directly in your `~/.hyper.js` config, use `hyperterm-visor#next`, apparently.

**Comment by RTSchriner** [comment]
@CWSpear I just tested about half of the anchor positions, so far so good. Anything I should be looking for in particular?

**Note: ** You need to restart Hyper for the changes to take affect.

**Comment by CWSpear** [comment]
I _think_ you can get away with a Full Reload (on Mac, Cmd-Shift-R) for changes to take effect.

Mostly that it does what you think it would; that it behaves in a logical way. And that different combinations work as expected.

**Comment by RTSchriner** [comment]
@CWSpear It does exactly what I expect it to do! Great work... love the plugin! 👍 If it wasn't for your plugin I'd still be using iTerm2.

**Comment by philwade** [comment]
Sort of a weird thing I found testing this. If I define no width in my config (but a height) on initial start the visor is 100% width. If I close the window and hit the hotkey, a new visor appears, correct height but odd width. Since this is outside the normal workflow (and I think the new window thing may have been introduced by the hotkey changes) it probably isn't super important to fix, but I thought you might want to know.

**Comment by CWSpear** [comment]
This repository is no longer maintained. Feel free to fork. Probably doesn't work with the latest version of Hyper 1, and certainly unlikely to work with Hyper 2.
