### ISSUE TITLE
Return focus to previous window when hiding visor.

### ISSUE THREAD

**Issue by pardom-zz** [CWSpear/hyperterm-visor#7]
If possible, I'd like the focus to return to the window which was active before invoking the visor hotkey when I invoke it to close the visor. Additionally, I would expect an option to close the visor when removing focus from the terminal window.

**Comment by CWSpear** [comment]
Ok, I'm gonna break up your comment into 3 points:

**Focus window to return to last window used**

This does make sense to me, but I still think we can do better. What about adding a little UI element so you can choose which window will be the Visor window and it will always be the Visow window until you change it to another?

**Hide visor when invoking hotkey**

It already does this. You said _close_, but I think you meant _hide_.

**Hide visor when it loses focus**

I have already considered adding this option, but I'll probably not make it default, but opt-in.

**Comment by pardom-zz** [comment]
Sorry if my comment was confusing. I didn't mean make the second point, since it's not an issue.

**Comment by CWSpear** [comment]
Ah, I did misread. My bad.

Ok, so you want it to return focus to the window of last _application_ that had focus (not the last HyperTerm window (unless it was the last thing to have focus!)).

Hmm... I agree that that definitely needs to be done, but I wonder how possible this is in the context of a plugin. I will investigate, though!

**Comment by pardom-zz** [comment]
Yes, that's exactly right. I'm not sure what's possible with the plugin API, but these are the things I like in iTerm's visor.

**Comment by CWSpear** [comment]
I think the best I could do is `app.hide()` which only works on macOS... This would mean if you hit the hotkey, you _couldn't_ get focus of another HyperTerm window if that was the last thing focused.

I can't find any way to focus last focused app with Electron.

**Comment by mattapperson** [comment]
@pardom @CWSpear https://github.com/zeit/hyperterm/issues/398

**Comment by nemo** [comment]
Any plans on doing this one? Seems like (as @mattapperson  linked to it) – you can do it by requiring electron and having access to the menu?

**Comment by nemo** [comment]
Turns out it's not as easy as using electron. Has to be OS specific. I made a version that works with OS X. (PR: #20)

**Comment by eness** [comment]
+1 I need this feature in my Windows 10 64bit box...

**Comment by adrianoresende** [comment]
@nemo macOS Sierra (10.12.1) not work for me =/

**Comment by CWSpear** [comment]
I'm on latest Mac with latest Terminal and version [0.3.0](https://github.com/CWSpear/hyperterm-visor/releases/tag/v0.3.0) of this plugin.

When I have 2 windows open and the Visor Window has focus and I hit the hotkey, the other window takes focus.

Does this differ from what people want/expect?

**Comment by CWSpear** [comment]
Ok, refreshing on all this... you want it to return focus to the last non-Hyper app, got it.

**Comment by CWSpear** [comment]
This should be resolved. Got some ideas from https://github.com/rickgbw/hyperterm-overlay. Not sure we really need 2 visor-esque apps, but here we are!

**Comment by masaeedu** [comment]
@CWSpear Make that 3 :) https://github.com/soutar/hyperterm-summon/

Regarding this issue, is this in the current release on npm? I'm not sure if this is the issue I'm facing, but I can't use my selected shortcut twice in a row on Windows. Once the window is minimized, pressing the shortcut again will not restore it until I click some other window to give it focus.

**Comment by CWSpear** [comment]
This should be on `npm`. I don't have an easy way to test on Windows tho :-(

It does sound related tho.
