### ISSUE TITLE
Only one instance of visor window.

### ISSUE THREAD

**Issue by pardom-zz** [CWSpear/hyperterm-visor#8]
Each additional terminal window I create beyond the first behaves as a visor. I would expect that only one terminal window behaves as a visor.

**Comment by CWSpear** [comment]
Only the most recent visor is shown/hidden with when you press the hotkey (but the other windows remain in the location/size they were as visor windows). This was listed in the caveats section. I'm looking into better alternatives. At least least, it _could_ restore non-visor windows to the size and positioning they were before you made them visor windows.

**Comment by CWSpear** [comment]
I have implemented this, but they made a change to `app.createWindow` that I would really like to get resolved before merging it in.

See zeit/hyper#976

**Comment by CWSpear** [comment]
See https://github.com/CWSpear/hyperterm-visor/releases/tag/v0.3.0
