### ISSUE TITLE
Option to hide window buttons and/or title.

### ISSUE THREAD

**Issue by pardom-zz** [CWSpear/hyperterm-visor#9]
I prefer to have a "windowless" aesthetic to my visor, as it is in iTerm2. The window buttons break down the visor aesthetic (as well as the rounded window corners). Not sure if this can be controlled in a plugin or in Electron, but an option would be nice.

**Comment by CWSpear** [comment]
I think it should be possible (just change some CSS!). I'll look into it. But probably after we figure out how to best handle what to make "the" Visor window, etc.

**Comment by CWSpear** [comment]
This is one of the next issues to tackle (if possible). 

I don't think it's possible to [remove the rounded corners](https://github.com/electron/electron/issues/414) from an Electron app... if you or anyone has any ideas on this, it'd be greatly appreciated.

**Comment by CWSpear** [comment]
This repository is no longer maintained. Feel free to fork. Probably doesn't work with the latest version of Hyper 1, and certainly unlikely to work with Hyper 2.
